
global:
  resolve_timeout: 5m

route:
  receiver: "default-receiver"
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  routes:
    - matchers:
        - severity="critical"
      receiver: "email-notification"
    - matchers:
        - severity="warning"
      receiver: "wmail-notification"

receivers:
  - name: "default-receiver"
    webhook_configs:
      - url: "http://grafana:3000/api/webhooks/alertmanager"

  - name: "email-notification"
    email_configs:
      - to: "admin@example.com"
        from: "alertmanager@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "user"
        auth_password: "password"
        require_tls: true


inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "job"]
