
global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['52.53.249.70:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['34.228.214.170:32601']

  - job_name: 'kube-apiserver'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['34.228.214.170:6443']

  - job_name: 'kube-scheduler'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['34.228.214.170:10259']

  - job_name: 'kube-controller-manager'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['34.228.214.170:10257']

  - job_name: 'kubelet'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['34.228.214.170:10250']
